# -*- coding: utf-8 -*-
"""titanicdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qT1imPcyjJXmq27HSxioLj2n9aZGzGpC
"""

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

dataset = pd.read_csv('/titanic.csv')
df = pd.DataFrame(dataset)

# x = df.iloc[:, 1:12].values
# y = df.iloc[:, 0].values
# x = df.iloc[:, [0,2,3,4,5,6,7,8,9,10,11]].values
# y = df.iloc[:, 1].values
x = df.drop('Survived')
y = df['Survived']


print(df.isnull().sum())

ctr = [1,3,10]
#ctr = [2,4,11]
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), ctr)], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

le = LabelEncoder()
y = le.fit_transform(y)
print(x, y)

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

sc = StandardScaler()
X_train[:, [0,2,3,4,5,6,7,8,9,10,11]] = sc.fit_transform(X_train[:, [0,2,3,4,5,6,7,8,9,10,11]])
print(X_train)

X_test[:, [0,2,3,4,5,6,7,8,9,10,11]] = sc.transform(X_test[:, [0,2,3,4,5,6,7,8,9,10,11]])
print(X_test)
